# Docker-Compose document
# Ref : https://docs.docker.com/compose/compose-file/

name: ${PROJECT_NAME}

services:
  server:
    image: ${SRV_IMAGE_NAME}
    container_name: ${SRV_CONTAINER_NAME}
    hostname: ${SRV_HOSTNAME}
    ports:
      - ${SRV_PORT}:80
    volumes:
      - ${PROJECT_DIR}/app:/usr/local/test
    networks:
      - srv-network

  nginx:
    image: nginx
    container_name: ${SRV_CONTAINER_NAME}-nginx
    ports:
      - 8081:80
    volumes:
      - ${PROJECT_DIR}/conf/docker/nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - srv-network

networks:
  srv-network:
    driver: bridge
    name: ${INFRA_DOCKER_NETWORK}
    external: true
